ARG RUBY_VERSION
FROM ruby:${RUBY_VERSION}

RUN apt-get update && \
  apt-get --no-install-recommends install -y \
    libcurl4 \
    libcurl4-openssl-dev \
    nginx && \
  apt-get autoremove -y && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists
